# Nombre para el workflow, será visible en la pestaña "Actions" de GitHub
name: News Bot

# Define cuándo se debe ejecutar este workflow
on:
  # 1. Se ejecuta en un horario programado (usando sintaxis de cron)
  schedule:
    # Esta configuración se ejecuta a los 30 minutos de cada hora (ej: 1:30, 2:30, etc.)
    # Si quisieras que fuera cada 15 minutos, usarías: '*/15 * * * *'
    - cron: '30 * * * *'
  
  # 2. Permite ejecutarlo manualmente desde la pestaña "Actions" para hacer pruebas
  workflow_dispatch:

# Otorga permisos de escritura al workflow para que pueda hacer "commit"
permissions:
  contents: write

# Define las tareas que se realizarán
jobs:
  build-and-commit:
    # El tipo de máquina virtual que usará GitHub para correr nuestro código
    runs-on: ubuntu-latest

    # La secuencia de pasos que componen la tarea
    steps:
      # Paso 1: Descarga el código de tu repositorio a la máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configura un entorno de Python en la máquina virtual
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Usamos una versión moderna y estable de Python

      # Paso 3: Instala las librerías que nuestro script de Python necesita
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      # Paso 4: Ejecuta tu script principal del bot
      - name: Run the bot script
        # Este bloque 'env' pasa de forma segura tus "Secrets" de GitHub al script
        env:
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python bot_script.py

      # Paso 5: Revisa si se crearon archivos nuevos y los sube automáticamente al repositorio
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # El mensaje que tendrán los commits hechos por el bot
          commit_message: "feat(bot): ✨ Add new flash news"
          # El autor que aparecerá en el historial de Git
          commit_author: "News Bot <actions@github.com>"